### ISSUE TITLE
error on compile 

### ISSUE THREAD

**Issue by joaojmendes** [koltyakov/node-sp-auth-config#4] opened 2017-10-21 20:29 UTC
Hi,

I have this error when compile my project. can you help me please to find why ?

Module not found: Error: Can't resolve 'readline' in '.../node_modules/node-sp-auth-config/node_modules/inquirer/lib/ui'

Thank you !

**Comment by koltyakov** [comment] 2017-10-21 20:52
Hi @joaojmendes,

Looks like some dependencies issue. Could you try deleting `node_modules` folder and run `npm install`? 

What version of `npm` do you use, bwt? If old one `npm i npm -g` might help.

**Comment by joaojmendes** [comment] 2017-10-21 21:06
Hi koltyakov,

Thank you for your quick answer .
Yes I deleted the node_modules an ran npm install but I have the same error.
npm version is 5.5.1.

thank you.

**Comment by koltyakov** [comment] 2017-10-21 21:47
Could you please share a list of dependencies and devDependencies from your package.json with versions?
I can't reproduce the issue.

**Comment by joaojmendes** [comment] 2017-10-22 09:28
I found the problem ... in the 
/.../node_modules/node-sp-auth-config/node_modules/inquirer/lib/ui/baseUI.js
had 
var readline = require('readline');
I changed to 
var readline = require('../utils/readline');

And resolved .

I'm working on React Project, scaffold with create-react-app with typescript .
Here the list of dependencies and devDependencies


  "name": "localspsite",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/prop-types": "^15.5.2",
    "@types/request-promise": "^4.1.38",
    "axios": "^0.17.0",
    "jwt-decode": "^2.2.0",
    "node-sp-auth": "^2.2.9",
    "node-sp-auth-config": "^2.0.9",
    "office-ui-fabric-react": "^5.11.0",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-scripts-ts": "2.8.0",
    "request-promise": "^4.2.2",
    "sp-pnp-js": "^3.0.1"
  },
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@types/jest": "^21.1.4",
    "@types/node": "^8.0.46",
    "@types/react": "^16.0.15",
    "@types/react-dom": "^16.0.2"
  }
}

Thank you very much.

**Comment by koltyakov** [comment] 2017-11-28 18:23
Closing this one. Feel free to reopen if any questions.

**Closed by koltyakov** 2017-11-28 18:23 UTC

**Comment by richie50** [comment] 2018-09-28 16:30
How is this closed if it was fixed in the node module. Do we have to create our own patch? @koltyakov @joaojmendes

**Comment by koltyakov** [comment] 2018-09-28 17:40
@richie50,

Can you describe the scenario when an issue exposes to you? And what is the issue?

This ticket issue isn't an issue at all,  mentioned `readline` is a native Node.js module which comes by default with core functionality. And there are no problems in `inquirer` dependency too as `require('readline')` and one in `/utils/readline` are just different things.
